import React, { useState } from 'react';
import type { ControlledMetricResult, ControlledResultsResponse } from '../api/types';
import { formatMetricCi, formatMetricValue, metricLabel, RQ_TITLES, rqInterpretation } from '../api/finalEvidence';
import { EvidenceBadge } from './EvidenceBadge';

const RQ_ORDER = ['RQ1', 'RQ2', 'RQ3', 'RQ4', 'RQ5', 'RQ6', 'RQ7'];

const AccountingItem: React.FC<{ value: string; label: string }> = ({ value, label }) => <div className="min-w-0 border-l border-neutral-200 pl-3 first:border-l-0 first:pl-0 dark:border-neutral-800"><p className="font-mono text-sm font-semibold text-neutral-900 dark:text-white">{value}</p><p className="mt-0.5 text-[10px] text-neutral-500">{label}</p></div>;

const MetricCell: React.FC<{ metric: ControlledMetricResult }> = ({ metric }) => <article className="rounded-lg border border-neutral-200 bg-neutral-50 p-3 dark:border-neutral-800 dark:bg-[#0a0a0a]"><div className="flex items-start justify-between gap-2"><div className="min-w-0"><p className="text-xs font-semibold text-neutral-900 dark:text-white">{metricLabel(metric)}</p>{(metric.judge || metric.condition) && <p className="mt-0.5 truncate text-[10px] text-neutral-500">{metric.judge ?? 'Overall'}{metric.condition ? ` · ${metric.condition}` : ''}</p>}</div><span className="shrink-0 font-mono text-[10px] text-neutral-500">{metric.value === null ? 'NOT ESTIMABLE' : metric.status}</span></div><p className="mt-2 text-xl font-mono font-semibold tracking-tight text-neutral-900 dark:text-white">{formatMetricValue(metric)}</p><p className="mt-1 text-[10px] leading-snug text-neutral-500">{formatMetricCi(metric)} · {metric.denominator === null ? 'N unavailable' : `N = ${metric.denominator}`}</p></article>;

const CompactRows: React.FC<{ metrics: ControlledMetricResult[] }> = ({ metrics }) => <div className="overflow-x-auto rounded-lg border border-neutral-200 dark:border-neutral-800"><table className="w-full min-w-[460px] text-left text-xs"><thead className="bg-neutral-50 text-[10px] font-mono uppercase tracking-wider text-neutral-500 dark:bg-[#0a0a0a]"><tr><th className="px-3 py-2 font-medium">Metric</th><th className="px-3 py-2 font-medium">Value</th><th className="px-3 py-2 font-medium">CI / N</th></tr></thead><tbody className="divide-y divide-neutral-200 dark:divide-neutral-800">{metrics.map((metric, index) => <tr key={`${metric.metric_key ?? metric.metric}-${index}`}><td className="px-3 py-2 text-neutral-700 dark:text-neutral-300">{metricLabel(metric)}{metric.judge ? <span className="block text-[10px] text-neutral-500">{metric.judge}</span> : null}</td><td className="whitespace-nowrap px-3 py-2 font-mono font-semibold text-neutral-900 dark:text-white">{formatMetricValue(metric)}</td><td className="whitespace-nowrap px-3 py-2 text-[10px] text-neutral-500">{formatMetricCi(metric)} · {metric.denominator === null ? 'N unavailable' : `N = ${metric.denominator}`}</td></tr>)}</tbody></table></div>;

const Tradeoff: React.FC<{ label: string; before?: ControlledMetricResult; after?: ControlledMetricResult; delta?: ControlledMetricResult }> = ({ label, before, after, delta }) => <div className="rounded-lg border border-neutral-200 bg-neutral-50 p-3 dark:border-neutral-800 dark:bg-[#0a0a0a]"><p className="text-[10px] font-mono font-medium uppercase tracking-wider text-neutral-500">{label}</p><div className="mt-2 flex items-baseline gap-2 font-mono"><span className="text-sm text-neutral-600 dark:text-neutral-400">{before ? formatMetricValue(before) : 'Unavailable'}</span><span className="text-neutral-400">→</span><span className="text-xl font-semibold tracking-tight text-neutral-900 dark:text-white">{after ? formatMetricValue(after) : 'Unavailable'}</span></div><p className="mt-1 text-[11px] text-neutral-500">{delta ? formatMetricValue(delta) : 'Delta unavailable'}</p></div>;

export const ControlledEvidencePanel: React.FC<{ data: ControlledResultsResponse | null; loading: boolean; error: string | null }> = ({ data, loading, error }) => {
  const [selectedRq, setSelectedRq] = useState('RQ1');
  if (loading) return <section className="rounded-lg border border-neutral-200 p-4 text-xs text-neutral-500 dark:border-neutral-800">Checking final RQ evidence…</section>;
  if (error) return <section className="rounded-lg border border-neutral-200 p-4 text-xs text-neutral-500 dark:border-neutral-800">Final results unavailable. No alternate evidence values are shown: {error}</section>;
  const empty = !data || data.status === 'NO_CONTROLLED_EVIDENCE';
  const pendingAnalysis = data?.status === 'CONTROLLED_RESULTS_PENDING_ANALYSIS';
  if (empty) return <section className="rounded-lg border border-dashed border-neutral-300 p-4 dark:border-neutral-700"><div className="flex items-center gap-2"><strong className="text-sm">NO CONTROLLED EVIDENCE</strong><EvidenceBadge evidenceClass="PLANNED" /></div><p className="mt-1 text-xs text-neutral-500">No final controlled analysis is available. Executed runs: {data?.executed_runs ?? 0}; passes: {data?.executed_passes ?? 0}.</p></section>;
  if (pendingAnalysis) return <section className="rounded-lg border border-dashed border-neutral-300 p-4 dark:border-neutral-700"><strong className="text-sm">CONTROLLED ANALYSIS NOT AVAILABLE</strong><p className="mt-1 text-xs text-neutral-500">{data.message}</p></section>;

  const metrics = data.results.filter((row) => row.rq === selectedRq);
  const byKey = (key: string) => metrics.find((row) => row.metric_key === key);
  const without = (keys: string[]) => metrics.filter((row) => !keys.includes(row.metric_key ?? ''));
  const primary = selectedRq === 'RQ1' ? [byKey('exact_agreement'), byKey('cohens_kappa')].filter(Boolean) as ControlledMetricResult[]
    : selectedRq === 'RQ2' ? [byKey('consistency')].filter(Boolean) as ControlledMetricResult[]
    : selectedRq === 'RQ3' ? ['paired_decisive_flip_rate', 'all_paired_disagreement_rate', 'slot_win_imbalance', 'incomplete_pairs'].map(byKey).filter(Boolean) as ControlledMetricResult[]
    : selectedRq === 'RQ4' || selectedRq === 'RQ5' ? ['variant_win_rate', 'original_win_rate', 'rejected_variant_count'].map(byKey).filter(Boolean) as ControlledMetricResult[]
    : [];
  const rq1Judges = metrics.filter((row) => row.metric_key?.startsWith('judge:'));
  const mainKeys = [...primary.map((row) => row.metric_key ?? ''), ...rq1Judges.map((row) => row.metric_key ?? '')];
  const detailMetrics = selectedRq === 'RQ7' ? metrics.filter((row) => !['baseline_agreement', 'dual_swap_agreement', 'agreement_delta', 'baseline_coverage', 'dual_swap_coverage', 'coverage_delta', 'dual_swap_dual_pass_stability'].includes(row.metric_key ?? '')) : without(mainKeys);

  return <section aria-label="Final controlled results" className="space-y-5">
    {data.accounting && <div className="grid gap-y-3 rounded-lg border border-neutral-200 bg-neutral-50 p-3 sm:grid-cols-2 sm:gap-x-3 lg:grid-cols-5 dark:border-neutral-800 dark:bg-[#0a0a0a]"><AccountingItem value={data.accounting.planned_units.toLocaleString()} label="units accounted" /><AccountingItem value={data.accounting.planned_pass_slots.toLocaleString()} label="pass slots" /><AccountingItem value={data.accounting.valid_returned_passes.toLocaleString()} label="valid returned" /><AccountingItem value={data.accounting.failed_pass_slots.toLocaleString()} label="failed slots" /><AccountingItem value={data.accounting.pending_units.toLocaleString()} label="pending" /></div>}
    <nav aria-label="Research question navigation" className="flex gap-1 overflow-x-auto border-b border-neutral-200 pb-2 dark:border-neutral-800">{RQ_ORDER.map((rq) => <button key={rq} type="button" onClick={() => setSelectedRq(rq)} className={`shrink-0 rounded px-3 py-1.5 text-xs font-mono transition-colors ${selectedRq === rq ? 'bg-neutral-900 text-white dark:bg-white dark:text-neutral-900' : 'text-neutral-600 hover:bg-neutral-100 dark:text-neutral-400 dark:hover:bg-neutral-900'}`}>{rq}</button>)}</nav>
    <section aria-labelledby="selected-rq-title"><div className="flex flex-col gap-2 sm:flex-row sm:items-baseline sm:justify-between"><div><h2 id="selected-rq-title" className="text-lg font-semibold text-neutral-900 dark:text-white">{selectedRq} · {RQ_TITLES[selectedRq]}</h2>{rqInterpretation(selectedRq) && <p className="mt-1 max-w-3xl text-xs leading-relaxed text-neutral-500">{rqInterpretation(selectedRq)}</p>}</div>{selectedRq !== 'RQ6' && <span className="font-mono text-[10px] text-neutral-500">Overall controlled result</span>}</div>
      {selectedRq === 'RQ6' ? <div className="mt-3 flex max-w-2xl flex-wrap items-center gap-x-3 gap-y-1 border-y border-neutral-200 py-3 dark:border-neutral-800"><p className="font-mono text-sm font-semibold text-neutral-900 dark:text-white">NOT ESTIMABLE</p><span className="rounded border border-neutral-300 px-1.5 py-0.5 font-mono text-[10px] text-neutral-600 dark:border-neutral-700 dark:text-neutral-300">UNBALANCED_PRESENTATION</span><p className="basis-full text-xs leading-relaxed text-neutral-500">The frozen design does not support a numeric matched source-family preference estimate.</p></div> : selectedRq === 'RQ7' ? <div className="mt-4 space-y-3"><div className="grid gap-3 sm:grid-cols-2"><Tradeoff label="Agreement" before={byKey('baseline_agreement')} after={byKey('dual_swap_agreement')} delta={byKey('agreement_delta')} /><Tradeoff label="Coverage" before={byKey('baseline_coverage')} after={byKey('dual_swap_coverage')} delta={byKey('coverage_delta')} /></div><div className="rounded-lg border border-neutral-200 p-3 text-xs dark:border-neutral-800"><span className="text-neutral-500">Dual-pass stability</span><span className="ml-3 font-mono font-semibold text-neutral-900 dark:text-white">{byKey('dual_swap_dual_pass_stability') ? formatMetricValue(byKey('dual_swap_dual_pass_stability')!) : 'Unavailable'}</span><p className="mt-1 text-[11px] text-neutral-500">Higher agreement among retained decisions, with lower valid coverage.</p></div></div> : <><div className={`mt-4 grid gap-3 ${selectedRq === 'RQ2' ? 'max-w-sm' : 'sm:grid-cols-2 xl:grid-cols-3'}`}>{primary.map((metric) => <MetricCell key={metric.metric_key ?? metric.metric} metric={metric} />)}</div>{selectedRq === 'RQ1' && rq1Judges.length > 0 && <div className="mt-4"><h3 className="mb-2 text-xs font-semibold text-neutral-700 dark:text-neutral-300">Per-judge alignment</h3><CompactRows metrics={[...rq1Judges].sort((a, b) => (b.value ?? -Infinity) - (a.value ?? -Infinity))} /></div>}</>}
      {detailMetrics.length > 0 && <details className="mt-4 border-t border-neutral-200 pt-3 dark:border-neutral-800"><summary className="cursor-pointer text-xs font-medium text-neutral-700 dark:text-neutral-300">Additional reported metrics ({detailMetrics.length})</summary><div className="mt-3"><CompactRows metrics={detailMetrics} /></div></details>}
    </section>
    <div className="flex items-center gap-3 border-t border-neutral-200 pt-3 text-xs dark:border-neutral-800"><EvidenceBadge evidenceClass="CONTROLLED" /><details><summary className="cursor-pointer font-medium text-neutral-700 dark:text-neutral-300">Provenance</summary><p className="mt-1 text-neutral-500">Pinned analysis and frozen-package references are retained with the final evidence.</p></details></div>
  </section>;
};
